### PR TITLE
Migrate from request to phin for performance enhancements!

### PR DESCRIPTION
**Pull request by ghost**
[phin](https://github.com/ethanent/phin) is a much more lightweight HTTP client library than request. :)

This PR reduces size of dependency to 1 from 50+, decreasing overall size. This PR should also improve HTTP request speed noticeably!

### CODE REVIEW

**Comment by bdsomer** [comment]
For further reference, [here's a tree](http://npm.anvaka.com/#/view/2d/request) of [`request`](https://npmjs.com/package/request). [`phin`](https://npmjs.com/package/phin) has a tree with just one node - itself.

Please merge this! Faster install times and faster performance will come from this pull request.

**Comment by simon-schlueter** [comment]
Sounds cool! Also sorry for the delay, haven't seen this earlier.

I will take a closer look at this next week but it looks good in theory. I haven't heard of that library (phin) before – how well tested is it?

**Comment by ethanent** [comment]
@CdePanda As the lead developer, I can say with confidence that phin is super stable and is tested quite thoroughly before releases! The full test script is available [right over here](https://github.com/ethanent/phin/blob/master/tests/test.js)!

**Comment by ethanent** [comment]
@CdePanda Have we got updates on this? 😁

**Pull request closed without merging**
